### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by Arun-UB** [Arun-UB/Unicloud#1]
Already fixed!
![capture](https://cloud.githubusercontent.com/assets/931533/3948501/6640d03e-26a7-11e4-94bb-e5eb51f173f9.PNG)

**Comment by Arun-UB** [comment]
Closing the issue!

**Comment by Arun-UB** [comment]
Reopen

**Comment by Arun-UB** [comment]
Changed title

**Comment by ManiMishra** [comment]
Hehaw
